<?php

/*
 * This file is part of the a Mlankatech (PTY) LTD Project.
 *
 * (c) Mfana Ronald Conco <ronald.conco@mlankatech.co.za>
 *
 * For the full copyright and license information, please view the LICENSE.
 *
 * Created At: 2016/09/27
 */
namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RadioShowRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class RadioShowRepository extends EntityRepository
{

    /**
     * @param $radioStation
     * @param $status
     * @param $startTime
     * @param $dayOfTheWeek
     * @return mixed
     */
    public function getShowByTimeSlot($radioStation,$status,$startTime,$dayOfTheWeek)
    {
        $qb = $this->createQueryBuilder('show')
            ->where('show.startTime <= :startTime')
            ->andWhere('show.radioStation = :radioStation')
            ->andWhere('show.status = :status');


        if(strtolower($dayOfTheWeek) == "sunday" ){
            $qb->andWhere('show.playsSunday = :dayOfTheWeek');
        }elseif (strtolower($dayOfTheWeek) == "monday"){
            $qb->andWhere('show.playsMonday = :dayOfTheWeek');
        }elseif (strtolower($dayOfTheWeek) == "tuesday"){
            $qb->andWhere('show.playsTuesday = :dayOfTheWeek');
        }elseif (strtolower($dayOfTheWeek) == "wednesday"){
            $qb->andWhere('show.playsWednesday = :dayOfTheWeek');
        }elseif (strtolower($dayOfTheWeek) == "thursday"){
            $qb->andWhere('show.playsThursday = :dayOfTheWeek');
        }elseif (strtolower($dayOfTheWeek) == "friday"){
            $qb->andWhere('show.playsFriday = :dayOfTheWeek');
        }elseif (strtolower($dayOfTheWeek) == "saturday"){
            $qb->andWhere('show.playsSaturday = :dayOfTheWeek');
        }

        $qb->setParameters(array(
                'startTime' => $startTime,
                'radioStation' => $radioStation,
                'status' => $status,
                'dayOfTheWeek' => true
            ));
        return $qb->getQuery()->execute();
    }
}
