<?php

/*
 * This file is part of the a Mlankatech (PTY) LTD Project.
 *
 * (c) Mfana Ronald Conco <ronald.conco@mlankatech.co.za>
 *
 * For the full copyright and license information, please view the LICENSE.
 *
 * Created At: 2016/09/27
 */
namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * StatusRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class StatusRepository extends EntityRepository
{
    /**
     * Get status by Code
     *
     * @param $code
     * @return mixed
     */
    public function getByCode($code)
    {
        $qb = $this->createQueryBuilder('status')
            ->where('status.code = :code')
            ->setParameter('code',$code);

        return $qb->getQuery()->getSingleResult();
    }
}