<?php
/*
 * This file is part of the a Mlankatech (PTY) LTD Project.
 *
 * (c) Mfana Ronald Conco <ronald.conco@mlankatech.co.za>
 *
 * For the full copyright and license information, please view the LICENSE.
 *
 * Created At: 2016/09/30
 */

namespace AppBundle\Repository;

use AppBundle\Entity\RadioStation;
use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{

    public function getUsersWhoCanApproveUploadedSong()
    {
        $qb = $this->createQueryBuilder('user')
            ->where('user.isAdmin = :isAdmin')
            ->setParameter('isAdmin',true);
        return $qb->getQuery()->getResult();
    }

    /**
     * @param RadioStation $radioStation
     * @return array
     */
    public function getRadioCompilersByRadioStation(RadioStation $radioStation)
    {
        $qb = $this->createQueryBuilder('user')
            ->where('user.isRadioStationCompiler = :isCompiler')
            ->andWhere('user.radioStation = :radioStation')
            ->setParameters(array(
                'isCompiler' => true,
                'radioStation' => $radioStation));
        return $qb->getQuery()->getResult();
    }
}