app:
    resource: "@AppBundle/Controller/"
    type:     annotation

sg_datatables_bundle:
    resource: "@SgDatatablesBundle/Controller/"
    type:     annotation

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

#oneup_uploader:
#    resource: .
#    type: uploader

_homepage:
    path:  /
    defaults: { _controller: AppBundle:Security:login }
    schemes:  [http]
